In [7]:
#Numpy Advance 
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a.shape)
b=np.zeros((2,2))
print(b)
c=np.ones((1,2))
print(c)
d=np.full((2,2),7)
print(d)
e=np.eye(2)
print(e)
f=np.random.random((2,2))
print(e)


<class 'numpy.ndarray'>
(3,)
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [3]:
b=[3,4,6,7]
print(type(b))
print(b)

<class 'list'>
[3, 4, 6, 7]


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b.shape)
print(b[0,0] ,b[0,1],b[1,0])

<class 'numpy.ndarray'>
(2, 3)
1 2 4


In [11]:
import numpy as np 
np.linspace(2.0,3.0,num=5)
np.linspace(2.0,3.0,num=5, endpoint=False)
np.linspace(2.0,3.0,num=5, retstep=True)


(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [11]:
import numpy as np 
np.linspace(2.0,3.0,num=5)
np.linspace(2.0,3.0,num=5, endpoint=False)
np.linspace(2.0,3.0,num=5, retstep=True)


(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [17]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:3]
print(a[0,1])
print(b)
print(a[:,:])
print(a[:2,1:3])
print(a[0:2,1:2])
print(a[2:3,0:2])
print(a[:2,1:])
#negative scling
print(a[-3:-1,-2:-1])
print(a[-2:1,1:3])

2
[[2 3]
 [6 7]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[2]
 [6]]
[[ 9 10]]
[[2 3 4]
 [6 7 8]]
[[3]
 [7]]
[]


In [20]:
# indexing allows you to construct arbitrary array using data from another array
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))
print(a[0,0],[1,1])
print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[1 4 5]
1 [1, 1]
[2 2]


In [22]:
import numpy as np 
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b=np.array([0,2,0,1])
print(a[np.arange(4), b])
a[np.arange(4) ,b] +=10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [23]:
import numpy as np 
a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [24]:
#datatype of Array element
import numpy as np
x=np.array([1,2])
print(x.dtype)
x=np.array([1,2], dtype=np.int64)
print(x.dtype)

int32
int64


In [26]:
import numpy as np
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x+y)
print(np.add(x,y))
print(x-y)
print(x*y)

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]


In [28]:
# importing numpy library 
import numpy as np 
  
# create numpy 2d-array 
m = np.array([[1, 2], 
              [2, 3]]) 
  
print("Printing the Original square array:\n", 
      m) 
  
# finding eigenvalues and eigenvectors 
w, v = np.linalg.eig(m) 
  
# printing eigen values 
print("Printing the Eigen values of the given square array:\n",
      w) 
  
# printing eigen vectors 
print("Printing Right eigenvectors of the given square array:\n",
      v)

Printing the Original square array:
 [[1 2]
 [2 3]]
Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
